### ISSUE TITLE
unable to add device manually

### ISSUE THREAD

**Issue by volkerrichert** [DrozmotiX/ioBroker.esphome#174] opened 2023-11-01 12:01 UTC
Wenn i try to add a new device manually, the console logs "Add device button executed", but nothing happens.

 - Adapter version: 0.3.1
 - admin 6.12
 - JS-Controller version: 4.0.12
 - Node version: 18.18.2

**Comment by DutchmanNL** [comment] 2023-11-01 12:06
> Wenn i try to add a new device manually, the console logs "Add device button executed", but nothing happens.
> 
> * Adapter version: 0.3.1
> * admin 6.12
> * JS-Controller version: 4.0.12
> * Node version: 18.18.2

cannot reproduce, are u sure the ip and password (must be the API password) is correct ?

**Comment by volkerrichert** [comment] 2023-11-03 11:57
yes, i'm sure. i tried multiple times. I'll crosscheck logs.

**Comment by DutchmanNL** [comment] 2023-11-03 12:02
> yes, i'm sure. i tried multiple times. I'll crosscheck logs.

yes please, I will need logging data/debug to see what's going wrong here as on my side all works fine :(

**Comment by DutchmanNL** [comment] 2023-11-03 15:46
@volkerrichert are u sure the adapter is running ? I can reproduce this issue only if the adapter instance is not active/running so I thin the issue is somehow related to that ?

**Comment by DutchmanNL** [comment] 2023-11-03 16:19
> ok, the new device seems to be offline, maybe so wifi issues... but when i try to add it, i'll see messages like "ESPHome error handling issue 192.168.120.60 TypeError: Cannot read properties of undefined (reading 'ip')"

ah thank you, here an error handling is missing will fix that. and indeed an offline device cannot be added device must be online to do that to initialise

**Comment by volkerrichert** [comment] 2023-11-04 13:55
ok, i got a message now. But if i type e.g. a wrong IP, i'm not able to delete that entry. It's not displayed but log will be "spammed" with "device unreachable". I have to restart the adapter. Can this be fixed somehow? Maybe a list of "unreachable devices" oder dummy entry ("unknown" values).

**Comment by DutchmanNL** [comment] 2023-11-04 23:26
> ok, i got a message now. But if i type e.g. a wrong IP, i'm not able to delete that entry. It's not displayed but log will be "spammed" with "device unreachable". I have to restart the adapter. Can this be fixed somehow? Maybe a list of "unreachable devices" oder dummy entry ("unknown" values). 

If you Like, a complete new way of managing devices will be introduced soon, currently only wled & enocean have this implemented and it's in alpha state (but we need testing feedback 😅)

You can support us by installing the "device manager" from git & latest version of wled from git (both versions not released to npm/latest yet) and try to manage (add/remove) a device

@Jey-Cee & would appreciate your feedback

**Comment by DutchmanNL** [comment] 2023-11-04 23:28
Link to repository https://github.com/Jey-Cee/ioBroker.device-manager

**Comment by DutchmanNL** [comment] 2023-11-05 11:56
please try v0.4.1-beto.0 from git

**Comment by volkerrichert** [comment] 2023-11-05 14:25
i installed device-manager & 0.4.1 BETA, but i can't see any differences. 

log still shows multiple EHOSTUNREACH
devices isn't show in adapter setting
device manager doesn't show anything. No instance is selectable.

**Comment by DutchmanNL** [comment] 2023-11-05 16:54
> log still shows multiple EHOSTUNREACH

please share the logs otherwise I cannot help

host unreach means device is not reachable by ip



> device manager doesn't show anything. No instance is selectable.

apologies I made a mistake, this comment was for an WLED issue not ESPHome

**Comment by volkerrichert** [comment] 2023-11-05 17:07
all i got is:



esphome.0 | Time | debug | Message
-- | -- | -- | --
esphome.0 | 2023-11-05 18:07:00.424 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:06:51.868 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:06:27.416 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:06:18.860 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:05:54.408 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:05:45.852 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:05:21.400 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:05:12.844 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:04:48.392 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:04:39.836 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:04:15.384 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:04:06.828 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:03:42.378 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:03:33.804 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053
esphome.0 | 2023-11-05 18:03:09.372 | error | ESPHome client 192.168.120.60 Error: connect EHOSTUNREACH 192.168.120.60:6053

**Comment by volkerrichert** [comment] 2023-11-05 17:13
and maybe, i'll install the git version of WLED and give DM a try. Maybe I'll add support in my adapers

**Closed** 2023-11-05 21:44 UTC
Labels: bug, fixed_TestingRequired
